
SET FOREIGN_KEY_CHECKS = 0;
DROP DATABASE IF EXISTS `616954`;
CREATE DATABASE `616954`; 
USE `616954`;

CREATE TABLE IF NOT EXISTS canzone (
  idcanzone INT NOT NULL,
  titolo VARCHAR(45) NOT NULL,
  artista VARCHAR(45) NOT NULL,
  durata VARCHAR(5) NOT NULL,
  PRIMARY KEY (idcanzone)
)ENGINE = InnoDB DEFAULT CHARSET = latin1;

CREATE TABLE IF NOT EXISTS nota (
  nome VARCHAR(3) NOT NULL,
  pathaudio VARCHAR(256) NOT NULL,
  pathimage VARCHAR(256) NOT NULL,
  PRIMARY KEY (nome)
)ENGINE = InnoDB DEFAULT CHARSET = latin1;

CREATE TABLE IF NOT EXISTS esecuzione (
  id INT NOT NULL AUTO_INCREMENT,
  idcanzone INT NOT NULL,
  nota VARCHAR(3) NOT NULL,
  tempo INT NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (idcanzone) REFERENCES canzone(idcanzone) ON DELETE CASCADE,
  FOREIGN KEY (nota) REFERENCES nota(nome) ON DELETE CASCADE
)ENGINE = InnoDB DEFAULT CHARSET = latin1;
